In [2]:
import numpy as np

In [3]:
#Insert element on a specific index in an array
a1 = np.array([1,2,3,4,5])
a2 = np.insert(a1,0,0, axis=0)
print(a2)


[0 1 2 3 4 5]


In [9]:
a1 = np.array([[1,2], [3,4]])
a2 = np.insert(a1, 1 , [5,6] , axis = 0) #inserting row-wise
a3 = np.insert(a1, 1 , [5,6] , axis = 1) #insertinf column-wise
print(a2)
print(a3)

[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]


In [5]:
#Append elements at the end of array
a3 = np.append(a2,[6,7,8,9])
print(a3)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Concatenate 2 arrays 1D
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [8]:
#Concatenate 2 arrays 2D
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr3 = np.concatenate((arr1,arr2) , axis=0) #vertical stacking
arr4 = np.concatenate((arr1,arr2) , axis=1) #horizontal stacking
print(arr3)
print(arr4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
#Deleting an array at a specific index
ar1 = np.array([1,2,3,4,5])
ar2 = np.delete(ar1, 2 , axis = 0)
print(ar2)

[1 2 4 5]


In [12]:
#Stacking in array -> Same as Concatenation (adds the elements to an existing axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
stack1 = np.vstack((array1,array2))
stack2 = np.hstack((array1,array2))
print(stack1)
print(stack2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [13]:
#stack() -> adds elements by adding a new axis (changes dimension of the array)
stack3 = np.stack((array1, array2), axis = 0)
print(stack3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
stack4 = np.stack((array1, array2), axis = 1)
print(stack4)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [16]:
#Spliting
array3 = np.array([1,2,3,4,5,6])
array4 = np.split(array3, 2) #it will give error if the array can be split in equal parts
print(array4)

[array([1, 2, 3]), array([4, 5, 6])]


In [22]:
#vsplit hsplit
array5 = np.array([[1,2], [3,4]])
array6 = np.vsplit(array5,2)
array7 = np.hsplit(array5,2)
print(array6)
print(array7)

[array([[1, 2]]), array([[3, 4]])]
[array([[1],
       [3]]), array([[2],
       [4]])]
