In [1]:
import numpy as np

In [2]:
#Broadcasting -> Allows operations between arrays of different shapes by automatically expanding dimensions when possible.
a1 = np.array([[1,2,3], [4,5,6]]) #2d array
a2 = np.array([10,20,30])
result = a1 * a2
print(result)

[[ 10  40  90]
 [ 40 100 180]]


In [3]:
#Expanding single elements (Scalar vs Array Operations)
mul = a1 * 2
print(mul)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
#Does not happen between incompatible shapes
a3 = np.array([1,2])
# add = a1+a3
# print(add) this would give error

In [6]:
#Vectorization -> performing operations on entire arrays at once instead of using Python loops.
addition = a1 + 5
print(addition)

[[ 6  7  8]
 [ 9 10 11]]
