In [1]:
import numpy as np

In [2]:
#Indexing -> O-based indexing
#Accessing elements from array
a1 = np.array([1,2,3,4,5])
print(a1[0])

1


In [3]:
#Negative Indexing
print(a1[-1])

5


In [4]:
#Slicing [start:stop:step]
a2 = np.array([10,20,30,40,50])
print(a2[0:])
print(a2[0::2])

[10 20 30 40 50]
[10 30 50]


In [5]:
#Reversing a list
print(a2[::-1])

[50 40 30 20 10]


In [6]:
#Fancy Indexing -> Selecting multiple elements at a time (at different positions)
print(a2[[0,1,3,2]])

[10 20 40 30]


In [8]:
#Boolean Masking -> Filtering elements of array
print(a2[a2>20])

[30 40 50]
