In [75]:
import numpy as np

In [76]:
#Check if sudoku is valid or not
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [77]:
#check if rows are valid
#check if columns are valid
#check if each 3x3 block is valid

In [78]:
s.sum(axis = 0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [79]:
s.sum(axis = 1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [80]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [81]:
#colums : [Age, Math Marks, Science Marks]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [82]:
#Get the shape of matrix
data.shape

(5, 3)

In [83]:
#Find the average age of students
np.mean(data[:,0])

np.float64(18.4)

In [84]:
#Extract math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [85]:
#Find the highest science marks
np.max(data[:,2])

np.int64(95)

In [86]:
#Get details of the students who scored more than 90 marks
data[data[:,1]>90]

array([[19, 92, 88]])

In [87]:
#Increase Math marks of all students by 5
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [88]:
#Find how many students are younger than 19
len(data[data[:,0]<19])

3

In [89]:
#Calculate the average marks in each subject(column - wise mean)
np.mean(data[:,1:] , axis = 0)

array([81.6, 83.2])

In [94]:
#Replace all science marks<75 with 0
data[:,2][data[:,2]<75]  = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])