In [2]:
import numpy as np

In [2]:
#Creating an array from a list
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
#Creating a 2D array
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#Default Values
a1 = np.zeros(5)

In [7]:
a1

array([0., 0., 0., 0., 0.])

In [10]:
a2 = np.ones((2,2))
a2

array([[1., 1.],
       [1., 1.]])

In [11]:
a3 = np.full((3,3), 5)
a3

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
#Creating a sequence
a4 = np.arange(0,10)
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a5 = np.arange(0,10,2)
a5

array([0, 2, 4, 6, 8])

In [14]:
#indentity matrix
a6 = np.eye(3)
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#random numbers
a7 = np.random.rand(5) # prints numbers between 0 and 1
print(a7)

[0.30726385 0.7725846  0.68538085 0.03966177 0.96385426]


In [11]:
a8 = np.random.randint(0,10,10) # prints number between the given range
print(a8)

[0 7 4 7 1 0 5 9 4 9]
