In [1]:
import numpy as np

In [4]:
#reshaping an array from 1D -> MultiDimensional
a1 = np.array([1,2,3,4,5,6])
b1 = a1.reshape(2,3)

In [8]:
b1[0][0] = 99

In [9]:
#Changing element in 'b1' also changes elements in 'b'
#so, Reshape does not create a copy it changes the view of the array
#(creates a new array object, but that object points to the same data in memory)
print(b1)
print(a1)

[[99  2  3]
 [ 4  5  6]]
[99  2  3  4  5  6]


In [11]:
#Flattening an array : Multidimensional array -> 1D
a2 = np.array([[1,2], [3,4]])
b2 = a2.flatten() #creates a copy so does not affect the elements in 'a2'

In [13]:
print(b2)
b2[1] = 99

[1 2 3 4]


In [15]:
print(b2)
print(a2)

[ 1 99  3  4]
[[1 2]
 [3 4]]


In [17]:
a3 = np.array([[1,2], [3,4]])
b3 = a3.ravel() #creates a view, so the changes in 'b3' affects 'a3' elements

In [18]:
print(b3)
b3[1] = 99

[1 2 3 4]


In [19]:
print(b3)
print(a3)

[ 1 99  3  4]
[[ 1 99]
 [ 3  4]]
