In [1]:
import numpy as np

In [2]:
#Sorting
a1 = np.array([1,5,3,8,0])
a2 = np.sort(a1)
print(a2)

[0 1 3 5 8]


In [3]:
#Sorting returning indexed
a3 = np.argsort(a1)
print(a3) #this returns indexed of the values in sorted order

[4 0 2 1 3]


In [5]:
#Returning index of minimum and maximum value
print(np.argmax(a1))
print(np.argmin(a1))

3
4


In [7]:
#Searching
print(np.where(a1>0)) #returns indexes

(array([0, 1, 2, 3]),)
